<?php

/**
 * ISO 639-1 dil kodları ve isimleri.
 * code  => [name (English), native]
 */
return [
    'af' => ['name' => 'Afrikaans',            'native' => 'Afrikaans'],
    'sq' => ['name' => 'Albanian',             'native' => 'Shqip'],
    'am' => ['name' => 'Amharic',              'native' => 'አማርኛ'],
    'ar' => ['name' => 'Arabic',               'native' => 'العربية'],
    'hy' => ['name' => 'Armenian',             'native' => 'Հայերեն'],
    'az' => ['name' => 'Azerbaijani',          'native' => 'Azərbaycan'],
    'eu' => ['name' => 'Basque',               'native' => 'Euskara'],
    'be' => ['name' => 'Belarusian',           'native' => 'Беларуская'],
    'bn' => ['name' => 'Bengali',              'native' => 'বাংলা'],
    'bs' => ['name' => 'Bosnian',              'native' => 'Bosanski'],
    'bg' => ['name' => 'Bulgarian',            'native' => 'Български'],
    'ca' => ['name' => 'Catalan',              'native' => 'Català'],
    'ceb'=> ['name' => 'Cebuano',              'native' => 'Cebuano'],
    'zh' => ['name' => 'Chinese',              'native' => '中文'],
    'co' => ['name' => 'Corsican',             'native' => 'Corsu'],
    'hr' => ['name' => 'Croatian',             'native' => 'Hrvatski'],
    'cs' => ['name' => 'Czech',                'native' => 'Čeština'],
    'da' => ['name' => 'Danish',               'native' => 'Dansk'],
    'nl' => ['name' => 'Dutch',                'native' => 'Nederlands'],
    'en' => ['name' => 'English',              'native' => 'English'],
    'eo' => ['name' => 'Esperanto',            'native' => 'Esperanto'],
    'et' => ['name' => 'Estonian',             'native' => 'Eesti'],
    'fi' => ['name' => 'Finnish',              'native' => 'Suomi'],
    'fr' => ['name' => 'French',               'native' => 'Français'],
    'fy' => ['name' => 'Frisian',              'native' => 'Frysk'],
    'gl' => ['name' => 'Galician',             'native' => 'Galego'],
    'ka' => ['name' => 'Georgian',             'native' => 'ქართული'],
    'de' => ['name' => 'German',               'native' => 'Deutsch'],
    'el' => ['name' => 'Greek',                'native' => 'Ελληνικά'],
    'gu' => ['name' => 'Gujarati',             'native' => 'ગુજરાતી'],
    'ht' => ['name' => 'Haitian Creole',       'native' => 'Kreyòl Ayisyen'],
    'ha' => ['name' => 'Hausa',                'native' => 'Hausa'],
    'he' => ['name' => 'Hebrew',               'native' => 'עברית'],
    'hi' => ['name' => 'Hindi',                'native' => 'हिन्दी'],
    'hu' => ['name' => 'Hungarian',            'native' => 'Magyar'],
    'is' => ['name' => 'Icelandic',            'native' => 'Íslenska'],
    'ig' => ['name' => 'Igbo',                 'native' => 'Igbo'],
    'id' => ['name' => 'Indonesian',           'native' => 'Bahasa Indonesia'],
    'ga' => ['name' => 'Irish',                'native' => 'Gaeilge'],
    'it' => ['name' => 'Italian',              'native' => 'Italiano'],
    'ja' => ['name' => 'Japanese',             'native' => '日本語'],
    'jv' => ['name' => 'Javanese',             'native' => 'Basa Jawa'],
    'kn' => ['name' => 'Kannada',              'native' => 'ಕನ್ನಡ'],
    'kk' => ['name' => 'Kazakh',               'native' => 'Қазақша'],
    'km' => ['name' => 'Khmer',                'native' => 'ភាសាខ្មែរ'],
    'rw' => ['name' => 'Kinyarwanda',          'native' => 'Ikinyarwanda'],
    'ko' => ['name' => 'Korean',               'native' => '한국어'],
    'ku' => ['name' => 'Kurdish',              'native' => 'Kurdî'],
    'ky' => ['name' => 'Kyrgyz',               'native' => 'Кыргызча'],
    'lo' => ['name' => 'Lao',                  'native' => 'ລາວ'],
    'la' => ['name' => 'Latin',                'native' => 'Latina'],
    'lv' => ['name' => 'Latvian',              'native' => 'Latviešu'],
    'lt' => ['name' => 'Lithuanian',           'native' => 'Lietuvių'],
    'lb' => ['name' => 'Luxembourgish',        'native' => 'Lëtzebuergesch'],
    'mk' => ['name' => 'Macedonian',           'native' => 'Македонски'],
    'mg' => ['name' => 'Malagasy',             'native' => 'Malagasy'],
    'ms' => ['name' => 'Malay',                'native' => 'Bahasa Melayu'],
    'ml' => ['name' => 'Malayalam',            'native' => 'മലയാളം'],
    'mt' => ['name' => 'Maltese',              'native' => 'Malti'],
    'mi' => ['name' => 'Maori',                'native' => 'Māori'],
    'mr' => ['name' => 'Marathi',              'native' => 'मराठी'],
    'mn' => ['name' => 'Mongolian',            'native' => 'Монгол'],
    'my' => ['name' => 'Myanmar (Burmese)',    'native' => 'မြန်မာ'],
    'ne' => ['name' => 'Nepali',               'native' => 'नेपाली'],
    'no' => ['name' => 'Norwegian',            'native' => 'Norsk'],
    'ny' => ['name' => 'Nyanja (Chichewa)',    'native' => 'Chichewa'],
    'or' => ['name' => 'Odia (Oriya)',         'native' => 'ଓଡ଼ିଆ'],
    'ps' => ['name' => 'Pashto',               'native' => 'پښتو'],
    'fa' => ['name' => 'Persian',              'native' => 'فارسی'],
    'pl' => ['name' => 'Polish',               'native' => 'Polski'],
    'pt' => ['name' => 'Portuguese',           'native' => 'Português'],
    'pa' => ['name' => 'Punjabi',              'native' => 'ਪੰਜਾਬੀ'],
    'ro' => ['name' => 'Romanian',             'native' => 'Română'],
    'ru' => ['name' => 'Russian',              'native' => 'Русский'],
    'sm' => ['name' => 'Samoan',               'native' => 'Samoa'],
    'gd' => ['name' => 'Scots Gaelic',         'native' => 'Gàidhlig'],
    'sr' => ['name' => 'Serbian',              'native' => 'Српски'],
    'st' => ['name' => 'Sesotho',              'native' => 'Sesotho'],
    'sn' => ['name' => 'Shona',                'native' => 'Shona'],
    'sd' => ['name' => 'Sindhi',               'native' => 'سنڌي'],
    'si' => ['name' => 'Sinhala',              'native' => 'සිංහල'],
    'sk' => ['name' => 'Slovak',               'native' => 'Slovenčina'],
    'sl' => ['name' => 'Slovenian',            'native' => 'Slovenščina'],
    'so' => ['name' => 'Somali',               'native' => 'Soomaali'],
    'es' => ['name' => 'Spanish',              'native' => 'Español'],
    'su' => ['name' => 'Sundanese',            'native' => 'Basa Sunda'],
    'sw' => ['name' => 'Swahili',              'native' => 'Kiswahili'],
    'sv' => ['name' => 'Swedish',              'native' => 'Svenska'],
    'tl' => ['name' => 'Tagalog (Filipino)',   'native' => 'Filipino'],
    'tg' => ['name' => 'Tajik',                'native' => 'Тоҷикӣ'],
    'ta' => ['name' => 'Tamil',                'native' => 'தமிழ்'],
    'tt' => ['name' => 'Tatar',                'native' => 'Татарча'],
    'te' => ['name' => 'Telugu',               'native' => 'తెలుగు'],
    'th' => ['name' => 'Thai',                 'native' => 'ภาษาไทย'],
    'tr' => ['name' => 'Turkish',              'native' => 'Türkçe'],
    'tk' => ['name' => 'Turkmen',              'native' => 'Türkmençe'],
    'uk' => ['name' => 'Ukrainian',            'native' => 'Українська'],
    'ur' => ['name' => 'Urdu',                 'native' => 'اردو'],
    'ug' => ['name' => 'Uyghur',               'native' => 'ئۇيغۇرچە'],
    'uz' => ['name' => 'Uzbek',                'native' => 'Oʻzbek'],
    'vi' => ['name' => 'Vietnamese',           'native' => 'Tiếng Việt'],
    'cy' => ['name' => 'Welsh',                'native' => 'Cymraeg'],
    'xh' => ['name' => 'Xhosa',               'native' => 'isiXhosa'],
    'yi' => ['name' => 'Yiddish',              'native' => 'ייִדיש'],
    'yo' => ['name' => 'Yoruba',               'native' => 'Yorùbá'],
    'zu' => ['name' => 'Zulu',                 'native' => 'isiZulu'],
];
